# Generated by Django 2.0.1 on 2018-02-09 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('dhiredate', models.DateField()),
                ('demail', models.EmailField(max_length=50)),
                ('dsal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DevGroup',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='devgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.DevGroup'),
        ),
    ]
