# Generated by Django 2.0.1 on 2018-02-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetJsData',
            fields=[
                ('Jsid', models.AutoField(primary_key=True, serialize=False, verbose_name='Jsid')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('imgUrl', models.CharField(max_length=100, verbose_name='imgUrl')),
                ('details', models.CharField(max_length=200, verbose_name='details')),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='devgroup',
        ),
    ]
