# Generated by Django 2.0.1 on 2018-02-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180226_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetJsData',
        ),
    ]
