# Generated by Django 2.0.1 on 2018-02-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_getjsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('dkey', models.CharField(max_length=30)),
                ('demail', models.EmailField(max_length=50)),
                ('dsex', models.FloatField()),
            ],
        ),
    ]
