# Generated by Django 2.0.1 on 2018-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDataCss',
            fields=[
                ('Jsid', models.AutoField(primary_key=True, serialize=False, verbose_name='Jsid')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('imgUrl', models.CharField(max_length=100, verbose_name='imgUrl')),
                ('details', models.CharField(max_length=200, verbose_name='details')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='dsex',
            field=models.CharField(max_length=30),
        ),
    ]
