# Generated by Django 2.0.1 on 2018-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180226_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDataHtml',
            fields=[
                ('Jsid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
    ]
