# Generated by Django 2.0.1 on 2019-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_getdatajavascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdatacss',
            name='CopyBook',
            field=models.CharField(default='asd', max_length=200),
        ),
    ]
