# Generated by Django 2.0.1 on 2019-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_getdatacss_copybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatacss',
            name='CopyBook',
            field=models.CharField(max_length=200),
        ),
    ]
