# Generated by Django 2.0.1 on 2019-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20190109_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatacss',
            name='CopyBook',
            field=models.CharField(default='', max_length=200),
        ),
    ]
