# Generated by Django 2.0.1 on 2019-01-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20190109_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getdatacss',
            name='CopyBook',
        ),
    ]
