# Generated by Django 2.0.1 on 2019-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_getdatacss_copybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdatacss',
            name='copyBook',
            field=models.IntegerField(default=1),
        ),
    ]
