# Generated by Django 2.0.1 on 2019-01-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20190111_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatacss',
            name='copyBook',
            field=models.IntegerField(default=10),
        ),
    ]
