# Generated by Django 2.0.1 on 2019-01-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20190111_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatacss',
            name='copyBook',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
