# Generated by Django 2.0.1 on 2019-01-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_getdatacss_copybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdatahtml',
            name='copyBook',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='getdatajavascript',
            name='copyBook',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='getdatacss',
            name='copyBook',
            field=models.IntegerField(default=1),
        ),
    ]
