# Generated by Django 2.0.1 on 2019-01-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_customercss_customerhtml_customerjavascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercss',
            name='borrowTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerhtml',
            name='borrowTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerjavascript',
            name='borrowTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
