# Generated by Django 2.0.1 on 2019-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_auto_20190111_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherRegister',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('dkey', models.CharField(max_length=30)),
                ('demail', models.EmailField(max_length=50)),
                ('dsex', models.CharField(max_length=30)),
            ],
        ),
    ]
