# Generated by Django 2.0.1 on 2019-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_teacherregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dQrCode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
