# Generated by Django 2.0.1 on 2019-01-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_register_daccessable'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregister',
            name='daccessable',
            field=models.IntegerField(default=1),
        ),
    ]
