# Generated by Django 2.0.1 on 2019-01-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_teacherregister_daccessable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='dsex',
        ),
    ]
