# Generated by Django 2.0.1 on 2019-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_remove_register_dsex'),
    ]

    operations = [
        migrations.CreateModel(
            name='yuoyu',
            fields=[
                ('Jsid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
