# Generated by Django 2.0.1 on 2019-01-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_yuoyu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yuoyu',
        ),
    ]
