# Generated by Django 2.0.1 on 2019-01-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_delete_yuoyu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerJavaScript',
        ),
    ]
