# Generated by Django 2.0.1 on 2019-01-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_customerjavascript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetDataJavaScript',
        ),
    ]
