# Generated by Django 2.0.1 on 2019-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_getdatajavascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdatacss',
            name='beBorrowedTimes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='getdatahtml',
            name='beBorrowedTimes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='getdatajavascript',
            name='beBorrowedTimes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='register',
            name='borrowTimes',
            field=models.IntegerField(default=1),
        ),
    ]
