# Generated by Django 2.0.1 on 2019-01-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_auto_20190114_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='borrowTimes',
        ),
    ]
