# Generated by Django 2.0.1 on 2019-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_remove_register_borrowtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='borrowTimes',
            field=models.IntegerField(default=0),
        ),
    ]
