# Generated by Django 2.0.1 on 2019-01-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_auto_20190114_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCss',
            fields=[
                ('Sid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Jsid', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('fee', models.IntegerField(default=0)),
                ('borrowTime', models.CharField(default='', max_length=100)),
                ('whoBorrow', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHtml',
            fields=[
                ('Sid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Jsid', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('fee', models.IntegerField(default=0)),
                ('borrowTime', models.CharField(default='', max_length=100)),
                ('whoBorrow', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerJavaScript',
            fields=[
                ('Sid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Jsid', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('fee', models.IntegerField(default=0)),
                ('borrowTime', models.CharField(default='', max_length=100)),
                ('whoBorrow', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
