# Generated by Django 2.0.1 on 2019-01-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_customercss_customerhtml_customerjavascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercss',
            name='Sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerhtml',
            name='Sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerjavascript',
            name='Sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
