# Generated by Django 2.0.1 on 2019-01-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0040_auto_20190114_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercss',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='customerhtml',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='customerjavascript',
            name='fee',
        ),
    ]
