# Generated by Django 2.0.1 on 2019-01-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0041_auto_20190114_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
